#pragma once
#include <QString>
#include <QDebug>
#include <QApplication>
#include <QWidget>
#include <QPushButton>
#include <QProgressBar>
#include <QVBoxLayout>
#include <QLabel>
#include <QLineEdit>